name: Recon Automation

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Tools
      run: |
        sudo apt update

        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        go install -v github.com/tomnomnom/assetfinder@latest
        go install -v github.com/owasp-amass/amass/v4/...@master
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
        go install -v github.com/lc/gau/v2/cmd/gau@latest
        go install -v github.com/projectdiscovery/katana/cmd/katana@latest

        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run Recon
      run: |
        domain="example.com"

        subfinder -d $domain -silent >> subs.txt
        assetfinder --subs-only $domain >> subs.txt
        amass enum -passive -d $domain >> subs.txt

        sort -u subs.txt -o subs.txt

        cat subs.txt | httpx -silent >> alive.txt

        cat alive.txt | gau >> urls.txt
        katana -list alive.txt -silent >> urls.txt

        sort -u urls.txt -o urls.txt

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: recon-results
        path: |
          subs.txt
          alive.txt
          urls.txt
