name: Auto Recon

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tools
      run: |
        sudo apt update
        sudo apt install -y golang git
        go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        go install github.com/projectdiscovery/httpx/cmd/httpx@latest

    - name: Run Recon
      run: |
        ~/go/bin/subfinder -d hilton.com -silent > subs.txt
        cat subs.txt | ~/go/bin/httpx -silent > live.txt

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: |
          subs.txt
          live.txt
