name: Ultimate Recon Stable

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:

      - name: Run Recon Container
        run: |
          docker run --rm projectdiscovery/pdcp \
          subfinder -d hilton.com -silent > subs.txt

      - name: Live Hosts
        run: |
          docker run --rm -i projectdiscovery/pdcp httpx -silent < subs.txt > live.txt

      - name: Nuclei Scan
        run: |
          docker run --rm -i projectdiscovery/pdcp nuclei -severity medium,high,critical < live.txt > nuclei.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: |
            subs.txt
            live.txt
            nuclei.txt 
